blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('website.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/website/urls.py
from django.urls import path, include
from .views import hello_blog
from .views import post_detail, save_form, contato, sobre_bellas_unhas

urlpatterns = [
    path('', hello_blog, name='home_blog'),
    path('post/<int:id>/',post_detail, name='post_detail'),
    path('save-form/',save_form, name='save_form'),
    path('contato/',contato, name='contato'),
    path('sobre/',sobre_bellas_unhas,name='sobre'),

]

blog/blog/models.py
from django.db import models
from utils.rands import slugify_new
from utils.images import resize_image
from django_summernote.models import AbstractAttachment
from django.contrib.auth.models import User

# Create your models here.

class PostAttachment(AbstractAttachment):
     def save(self, *args, **kwargs):
         if not self.name:
             self.name = self.file.name
 
         current_file_name = str(self.file.name)
         super_save = super().save(*args, **kwargs)
         file_changed = False
 
         if self.file:
             file_changed = current_file_name != self.file.name
 
         if file_changed:
             resize_image(self.file, 900, True, 70)
 
         return super_save
 
 
class Tag(models.Model):
     class Meta:
         verbose_name = 'Tag'
         verbose_name_plural = 'Tags'
 
     name = models.CharField(max_length=255)
     slug = models.SlugField(
         unique=True, default=None,
         null=True, blank=True, max_length=255,
     )
 
     def save(self, *args, **kwargs):
         if not self.slug:
             self.slug = slugify_new(self.name, 4)
         return super().save(*args, **kwargs)
 
 
class Category(models.Model):
     class Meta:
         verbose_name = 'Category'
         verbose_name_plural = 'Categories'
 
     name = models.CharField(max_length=255)
     slug = models.SlugField(
         unique=True, default=None,
         null=True, blank=True, max_length=255,
     )
 
     def save(self, *args, **kwargs):
         if not self.slug:
             self.slug = slugify_new(self.name, 4)
         return super().save(*args, **kwargs)
        

     def __str__(self) -> str:
         return self.name
 

class Page(models.Model):
     class Meta:
        verbose_name = 'Page'
        verbose_name_plural = 'Pages'
     title = models.CharField(max_length=65,)
     slug = models.SlugField(
         unique=True, default="",
         null=False, blank=True, max_length=255
     )
     is_published = models.BooleanField(
         default=False,
         help_text=(
             'Este campo precisará estar marcado '
             'para a página ser exibida publicamente.'
         ),
     )
     content = models.TextField()
 
     def save(self, *args, **kwargs):
         if not self.slug:
             self.slug = slugify_new(self.title, 4)
         return super().save(*args, **kwargs)
 
     def __str__(self) -> str:
         return self.title


class Post(models.Model):
     class Meta:
         verbose_name = 'Post'
         verbose_name_plural = 'Posts'
 
     title = models.CharField(max_length=65,)
     slug = models.SlugField(
         unique=True, default="",
         null=False, blank=True, max_length=255
     )
     excerpt = models.CharField(max_length=150)
     is_published = models.BooleanField(
         default=False,
         help_text=(
             'Este campo precisará estar marcado '
             'para o post ser exibido publicamente.'
         ),
     )
     content = models.TextField()
     cover = models.ImageField(upload_to='posts/%Y/%m/', blank=True, default='')
     ### cover = models.ImageField(upload_to='posts/%Y/%m/', blank=True, null=True)

     cover_in_post_content = models.BooleanField(
         default=True,
         help_text='Se marcado, exibirá a capa dentro do post.',
     )
     created_at = models.DateTimeField(auto_now_add=True)
     # user.post_created_by.all
     created_by = models.ForeignKey(
         User,
         on_delete=models.SET_NULL,
         blank=True, null=True,
         related_name='post_created_by'
     )
     updated_at = models.DateTimeField(auto_now=True)
     # user.post_updated_by.all
     updated_by = models.ForeignKey(
         User,
         on_delete=models.SET_NULL,
         blank=True, null=True,
         related_name='post_updated_by'
     )
     category = models.ForeignKey(
         Category, on_delete=models.SET_NULL, null=True, blank=True,
         default=None,
     )
     tags = models.ManyToManyField(Tag, blank=True, default='')
 
     def __str__(self):
         return self.title
 
     def save(self, *args, **kwargs):
         if not self.slug:
             self.slug = slugify_new(self.title, 4)
         #return super().save(*args, **kwargs)
         current_cover_name = str(self.cover.name)
         super_save = super().save(*args, **kwargs)
         cover_changed = False
 
         if self.cover:
             cover_changed = current_cover_name != self.cover.name
 
         if cover_changed:
             resize_image(self.cover, 900, True, 70)
 
         return super_save
     

blog/website/models.py
from django.db import models

# Create your models here.
#

class Categories(models.TextChoices):
    TECH = "TC", 'Tecnologia'
    SALAOBLZ  = 'BE', 'Salao Beleza'
    CR = 'CR', 'Curiosidade'
    GR = 'GR', 'Geral'
    
class Contact(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self) -> str:
        return self.name
    
class Post(models.Model):
    title = models.CharField(max_length=100)
    sub_title= models.CharField(max_length=200)
    content = models.TextField()
    categories = models.CharField(
        max_length=2,
        choices=Categories.choices,
        default=Categories.GR,
    )
    deleted = models.BooleanField(default=False)
    imagem = models.ImageField(upload_to='posts', null=True, blank=True)
    
    def __str__(self):
        return self.title
    
    def full_name(self):
        return self.title + self.sub_title
    
    # def get_category_label(self):
    #     return self.categories
    
    
    full_name.admin_order_field = 'title'

blog/blog/views.py
from django.http import HttpResponse
import datetime

def hello_world(request):
    return HttpResponse('Hello_World, Givaldo')

def current_datetime(request):
    now = datetime.datetime.now()
    html = '<html><body>It is now %s.</body></html>' % now
    return HttpResponse(html)

blog/website/views.py
from django.shortcuts import render
from .models import Post, Contact

# Create your views here.

def hello_blog(request):
      list = [
            'Django', 'Python', 'Git', 'Html', 
            'Banco de Dados', 'Linux', 'Nginx', 'Uwsgi',
            'Systemclt'
      ]
      list_posts = Post.objects.filter(deleted=False)
      data ={'name': 'Curso de Django 3', 'lista_tecnologias':list,
             'posts': list_posts
             }
      return render(request, 'index.html', data)

    
def post_detail(request, id):
      post = Post.objects.get(id=id)
      return render(request, 'post_detail.html',{'post': post})

def save_form(request):
      name=request.POST['name']
      Contact.objects.create(
            name=name,
            email=request.POST['email'],
            message=request.POST['message']
      )
      return render(request, 'contact_success.html', {'name_contact': name})

def contato(request):
      return render(request, 'contato.html')

def sobre_bellas_unhas(request):
      return render(request, 'sobre_bellas_unhas.html')

blog/blog/templates/blog/base copy.html
<!DOCTYPE html>
<html lang="pt-br">
 <head>
   {% include 'blog/partials/_head.html' %}
 </head>
 
 <body class="dark-theme"> 
   {% include 'blog/partials/_header.html' %}
 
   {% block content %}{% endblock content %}
 
   {% include 'blog/partials/_pagination.html' %}
 
   {% include 'blog/partials/_footer.html' %}
 
   {% include 'blog/partials/_temp.html' %}
 </body>
 </html>

blog/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
  {% include 'blog/partials/_head.html' %}
  {% block additional_head %}{% endblock additional_head %}
</head>

<body>
  <div class="blog-wrapper">
    {% if site_setup.show_header %}
      {% include 'blog/partials/_header.html' %}
    {% endif %}

    {% block content %}{% endblock content %}
    
    {% if site_setup.show_pagination %}
      {% include 'blog/partials/_pagination.html' %}
    {% endif %}

    {% if site_setup.show_footer %}
      {% include 'blog/partials/_footer.html' %}
    {% endif %}
  </div>
</body>
</html>

blog/blog/templates/blog/pages/index copy.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1> Olá Mundo </h1>
{% endblock content %}

blog/blog/templates/blog/pages/index.html
{% extends 'blog/base.html' %}

{% block content %}
  <main class="main-content section-wrapper">
    <div class="section-content-wide">
      <div class="section-gap">

        <div class="card-grid">
          {% for i in ""|ljust:"9" %}
            {% include 'blog/partials/_post-card.html' with i=forloop.counter0 %}
          {% endfor %}
        </div>

      </div>
    </div>
  </main>
{% endblock content %}

blog/blog/templates/blog/pages/page.html
{% extends 'blog/base.html' %}

{% block content %}
  <main class="main-content section-wrapper">
    <div class="section-content-narrow">
      <div class="section-gap">
        <h1 class="center">{{ page.title }}</h1>
        {{ page.content | safe }}
      </div>
    </div>
  </main>
{% endblock content %}

blog/blog/templates/blog/pages/post copy.html
{% extends 'blog/base.html' %} 

{% block additional_head %}
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/codemirror.min.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/theme/dracula.min.css">

<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/codemirror.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/python/python.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/javascript/javascript.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/htmlmixed/htmlmixed.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/css/css.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/xml/xml.min.js"></script>
{% endblock additional_head %}

{% block content %}
<main class="main-content single-post section-wrapper">
  <div class="single-post-content section-content-narrow">
    <div class="single-post-gap section-gap">

      {% if post.cover and post.cover_in_post_content %}
        <div class="single-post-cover pb-base">
          <img 
            loading="lazy" 
            src="{{ post.cover.url }}" 
            alt="{{ post.title }}"
          >
        </div>
      {% endif %}

      <h2 class="single-post-title pb-base center">
        {{ post.title }}
      </h2>

      <div class="post-meta pb-base">
        <div class="post-meta-item">
          <a 
            class="post-meta-link" 
            href="{% url 'blog:created_by' post.created_by.pk  %}"
          >
            <i class="fa-solid fa-user"></i>
            <span>
              {% if post.created_by.first_name %}
                {{ post.created_by.first_name }} 
                {{ post.created_by.last_name }}
              {% else %}
                {{ post.created_by.username }}
              {% endif %}
            </span>
          </a>
        </div>
        <div class="post-meta-item">
          <span class="post-meta-link">
            <i class="fa-solid fa-calendar-days"></i>
            <span>
              {{ post.created_at | date:'d/m/Y \à\s H:i' }}
            </span>
          </span>
        </div>

        {% if post.category %}
          <div class="post-meta-item">
            <a 
              class="post-meta-link" 
              href="{% url 'blog:category' post.category.slug  %}"
            >
              <i class="fa-solid fa-tag"></i>
              <span>
                {{ post.category.name }}
              </span>
            </a>
          </div>
        {% endif %}
      
      </div>

      <p class="single-post-excerpt pb-base">
        {{ post.excerpt | safe }}
      </p>

      <div class="separator"></div>

      <div class="single-post-content">
        {{ post.content | safe  }} 
      
        {% if post.tags.exists %}
          <div class="post-tags">
            <span>Tags: </span>

            {% for tag in post.tags.all %}
              <a class="post-tag-link" href="{% url 'blog:tag' tag.slug %}">
                <i class="fa-solid fa-link"></i>
                <span>{{ tag.name }}</span>
              </a>
            {% endfor %}
          </div>
        {% endif %}
        
      </div>
    
    </div>
  </div>
</main>

{% endblock content %}

blog/blog/templates/blog/pages/post.html
{% extends 'blog/base.html' %} 

{% block content %}
<main class="main-content single-post section-wrapper">
  <div class="single-post-content section-content-narrow">
    <div class="single-post-gap section-gap">
      <div class="single-post-cover pb-base">
        <img loading="lazy" src="https://picsum.photos/1920/1080/?rand=12" alt="Change me">
      </div>

      <h2 class="single-post-title pb-base center">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      </h2>

      <div class="post-meta pb-base">
        <div class="post-meta-item">
          <a class="post-meta-link" href="#">
            <i class="fa-solid fa-user"></i>
            <span>
              Author Full Name
            </span>
          </a>
        </div>
        <div class="post-meta-item">
          <a class="post-meta-link" href="#">
            <i class="fa-solid fa-calendar-days"></i>
            <span>
              20/04/2023
            </span>
          </a>
        </div>
        <div class="post-meta-item">
          <a class="post-meta-link" href="#">
            <i class="fa-solid fa-tag"></i>
            <span>
              Categoria
            </span>
          </a>
        </div>
      </div>

      <p class="single-post-excerpt pb-base">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore, vero
        fugiat eum perferendis accusamus enim quos obcaecati. Voluptates a vel
        obcaecati ipsa in dignissimos facere odio et, ab provident assumenda!
      </p>

      <div class="separator"></div>

      <div class="single-post-content">
        {% include 'blog/partials/_temp.html' %} 
      
        <div class="post-tags">
          <span>Tags: </span>

          <a class="post-tag-link" href="#">
            <i class="fa-solid fa-link"></i>
            <span>Testando</span>
          </a>

          <a class="post-tag-link" href="#">
            <i class="fa-solid fa-link"></i>
            <span>Atenção</span>
          </a>

          <a class="post-tag-link" href="#">
            <i class="fa-solid fa-link"></i>
            <span>Obrigado</span>
          </a>

          <a class="post-tag-link" href="#">
            <i class="fa-solid fa-link"></i>
            <span>Educação</span>
          </a>

          <a class="post-tag-link" href="#">
            <i class="fa-solid fa-link"></i>
            <span>Python</span>
          </a>

        </div>
        
      </div>
    
    </div>
  </div>
</main>

{% endblock content %}

blog/blog/templates/blog/partials/_footer.html
<footer class="footer section-wrapper mt-base">
    <div class="section-content-wide">
      <div class="section-gap">
        <div class="center">
          © {% now "Y" %} {{ site_setup.title }} - Todos os direitos reservados.
        </div>
      </div>
    </div>
  </footer>
  
  <script>
    (function () {
      if (typeof CodeMirror == 'undefined') return;
  
      const codes = document.querySelectorAll('pre');
  
      for (const code of codes) {
        const language = code.dataset.language || null;
        const text = code.textContent || code.innerText;
  
        const config = {
          value: text,
          tabSize: 2,
          mode: language,
          theme: 'dracula',
          lineNumbers: true,
          styleActiveLine: true,
          styleActiveSelected: true,
          lineWrapping: false,
          line: true,
          readOnly: true,
          viewportMargin: 50,
          matchBrackets: true,
        };
  
        const editor = CodeMirror(function (node) {
          code.parentNode.replaceChild(node, code);
        }, config);
      }
    })();
  </script>
  
  

blog/blog/templates/blog/partials/_head copy.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=b, initial-scale=1.0">
<link rel="icon" href="/favicon.ico" type="image/x-icon">
<link rel="stylesheet" href="{% static 'blog/css/remedy.css' %}">
<link rel="stylesheet" href="{% static 'blog/css/style.css' %}">

{% if site_setup.favicon %}
    <link rel="shortcut icon" href="{{ site_setup.favicon.url }}" type="image/png">
{% endif %}

<title>Testando Blog</title>

blog/blog/templates/blog/partials/_head.html
{% load static %}
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="{% static 'blog/css/remedy.css' %}">
<link rel="stylesheet" href="{% static 'blog/css/style.css' %}">

{% if site_setup.favicon %}
  <link rel="shortcut icon" href="{{ site_setup.favicon.url }}" type="image/png">
{% endif %}

<title>{{ site_setup.title }}</title>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

blog/blog/templates/blog/partials/_header copy.html
<header class="header section-wrapper">
    <div class="section-content-wide">
      <div class="section-gap">
  
        <h1 class="blog-title center pb-base">
          <a class="blog-link" href="/">{{ site_setup.title }}</a>
        </h1>
        
        {% if site_setup.show_description %}
          <p class="blog-description pb-base center">{{ site_setup.description }}</p>
        {% endif %}
  
        {% if site_setup.show_search %}
          <div class="search pb-base center">
            <form class="search-form" action="{% url 'blog:search' %}" method="get">
              <div class="search-content">
                <label class="sr-only" id="search-label" for="search-input">Search</label>
                <input
                  class="search-input"
                  type="search"
                  name="search"
                  id="search-input"
                  placeholder="Search"
                  value="{{ search_value }}"
                  required
                >
                <button class="search-btn" type="submit" aria-labelledby="search-label">
                  <i class="fa fa-search"></i>
                </button>
              </div>
            </form>
          </div>
        {% endif %}


        #=======================================================
        <header class="header section-wrapper">
          <div class="section-content-wide">
            <div class="section-gap">
        
              <h1 class="blog-title center pb-base">
                <a class="blog-link" href="/"> Blog do Luiz </a>
              </h1>
              
              <p class="blog-description pb-base center">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ipsam
                neque explicabo sequi, voluptas saepe porro atque provident, reiciendis
                natus harum labore nisi eum consectetur cumque minima dolorem adipisci?
                Dolores?
              </p>
        
              <div class="search pb-base center">
                <form class="search-form" action="#" method="get">
                  <div class="search-content">
                    <label class="sr-only" id="search-label" for="search-input">Search</label>
                    <input
                      class="search-input"
                      type="search"
                      name="search"
                      id="search-input"
                      placeholder="Search"
                      value="Non risu potius quam oratione eiciendum? Quo pleb "
                    >
                    <button class="search-btn" type="submit" aria-labelledby="search-label">
                      <i class="fa fa-search"></i>
                    </button>
                  </div>
                </form>
              </div>
        
              <nav class="menu">
                <ul class="menu-items">
                  <li class="menu-item">
                    <a class="menu-link" href="/post/">Post</a>
                  </li>
                  <li class="menu-item">
                    <a class="menu-link" href="/page/">Page</a>
                  </li>
                  <li class="menu-item">
                    <a class="menu-link" href="#">About us</a>
                  </li>
                  <li class="menu-item">
                    <a class="menu-link" href="#">Contact</a>
                  </li>
                  <li class="menu-item">
                    <a class="menu-link" href="#">Support</a>
                  </li>
                </ul>
              </nav>
              
            </div>
          </div>
        </header>
        #===========================

  
        {% if site_setup.show_menu %}
          <nav class="menu">
            <ul class="menu-items">
              {% for link in site_setup.menu.all %}
                <li class="menu-item">
                  {% if link.new_tab %}
                    <a target="_blank" class="menu-link" href="{{ link.url_or_path }}">
                      {{ link.text }}
                    </a>
                {% else %}
                    <a class="menu-link" href="{{ link.url_or_path }}">
                      {{ link.text }}
                    </a>
                  {% endif %}
                </li>
              {% endfor %}
            </ul>
          </nav>
        {% endif %}
        
      </div>
    </div>
  </header>
  

blog/blog/templates/blog/partials/_header.html
<header class="header section-wrapper">
  <div class="section-content-wide">
    <div class="section-gap">

      <h1 class="blog-title center pb-base">
        <a class="blog-link" href="/"> {{ site_setup.title }} </a>
      </h1>
       
      {% if site_setup.show_description %}
          <p class="blog-description pb-base center">{{ site_setup.description }}</p>
      {% endif %}

      {% if site_setup.show_search %}
        <div class="search pb-base center">
          <form class="search-form" action="#" method="get">
            <div class="search-content">
              <label class="sr-only" id="search-label" for="search-input">Search</label>
              <input
                class="search-input"
                type="search"
                name="search"
                id="search-input"
                placeholder="Search"
                value="Non risu potius quam oratione eiciendum? Quo pleb "
              >
              <button class="search-btn" type="submit" aria-labelledby="search-label">
                <i class="fa fa-search"></i>
              </button>
            </div>
          </form>
        </div>
      {% endif %}
        
      {% if site_setup.show_menu %}
         <nav class="menu">
           <ul class="menu-items">
              {% for link in site_setup.menu.all %}
               <li class="menu-item">
                  {% if link.new_tab %}
                   <a target="_blank" class="menu-link" href="{{ link.url_or_path }}">
                     {{ link.text }}
                   </a>
                  {% else %}
                   <a class="menu-link" href="{{ link.url_or_path }}">
                     {{ link.text }}
                   </a>
                  {% endif %}
               </li>
              {% endfor %}
           </ul>
         </nav>
      {% endif %}
 
    </div>
  </div>
</header>

blog/blog/templates/blog/partials/_pagination.html
{% if page_obj and page_obj.has_other_pages %}

<div class="separator"></div>

<div class="pagination-wrapper section-wrapper">
  <div class="pagination-content section-content-wide">
    <div class="pagination-gap section-gap">

      <nav class="pagination-links" aria-label="Pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
              <a title="Page 1" aria-label="Page 1" href="?page=1{{ search_url }}">
                  <i class="fa-solid fa-backward-fast"></i>
              </a>
              <a title="Page {{ page_obj.previous_page_number }}" aria-label="Page {{ page_obj.previous_page_number }}" href="?page={{ page_obj.previous_page_number }}{{ search_url }}">
                <i class="fa-solid fa-circle-chevron-left"></i>
              </a>
            {% else %}
              <span title="Current page" aria-current="page">
                <i class="fa-solid fa-circle-chevron-up"></i>
              </span>          
            {% endif %}

            <span class="current" title="Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}" aria-current="page">
              {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
            </span>

            {% if page_obj.has_next %}
              <a title="Page {{ page_obj.next_page_number }}" aria-label="Page {{ page_obj.next_page_number }}" href="?page={{ page_obj.next_page_number }}{{ search_url }}">
                <i class="fa-solid fa-circle-chevron-right"></i>
              </a>
              <a title="Page {{ page_obj.paginator.num_pages }}" aria-label="Page {{ page_obj.paginator.num_pages }}" href="?page={{ page_obj.paginator.num_pages }}{{ search_url }}">
                <i class="fa-solid fa-forward-fast"></i>
              </a>
            {% else %}
              <span title="Current page" aria-current="page">
                <i class="fa-solid fa-circle-chevron-up"></i>
              </span>          
            {% endif %}
        </span>
      </nav>
      
    </div>
  </div>
</div>

{% endif %}

blog/blog/templates/blog/partials/_post-card.html
<article class="card">
  
    <div class="card-cover-wrapper">
      <a href="#" class="card-cover-link">
        <img 
          class="card-cover"
          loading="lazy"
          src="https://picsum.photos/745/419/?rand=2{{ i }}" 
          alt="Change me"
        >
      </a>
    </div>
  
    <div class="card-text-wrapper">
      <div class="card-title-wrapper">
        <h2 class="card-title">
          <a href="#" class="card-title-link">
            Lorem ipsum dolor sit amet.
          </a>
        </h2>
      </div>
  
      <div class="card-content-wrapper">
        <p class="card-content">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur nulla omnis, maiores tempore pariatur a obcaecati atque deserunt reiciendis quam! 
        </p>
  
        <div class="card-actions">
          <a class="card-action-link" href="#">
            <span>Read</span>
            <i class="fa-solid fa-circle-arrow-right"></i>
          </a>
        </div>
      </div>
    </div>
  
  </article>

blog/website/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Bellas Unhas - Blog</title>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/estilo.css' %}">
</head>
<body>

	<div id="area-cabecalho">

		<div id="area-logo">
			<h1>Bellas <span class="branco"> Unhas</span></h1>
		</div>
		<div id="area-menu">
			<a href="/blog">Home</a>
			<a href="">Blog</a>
			<a href="{% url 'sobre' %}">Sobre</a>
			<a href="{% url 'contato' %}">Contato</a>
		</div>

	</div>

	<div id="area-principal">

		<div id="area-postagens">			
			<!-- abertura postagem -->
			<div class="postagens-grid"> 
				{% for post in posts %}
					<div class="postagem">
						<h2>{{ post.title }}</h2>
															
						{% if post.imagem %}
							<img src="{{ post.imagem.url }}" 
							alt="Imagem do post" width="100px" 
							height="120px">						
						{% else %}
							<img width="100px" height="120px"
							src="{% static 'images/imagem8.jpeg' %}">
						{% endif %}
				
						<p>
							{{ post.sub_title }}
							<br>
							{{ post.get_categories_display }}
						</p>					
						<a href="{% url 'post_detail' post.id %}" class="button">Leia mais</a>
						<br>
						<hr>				
					</div>					
				{% endfor %}
			</div><!--// fechamento postagem -->
		</div>

		<div id="area-lateral">
			<div class="conteudo-lateral">
				<h3>Postagens recentes</h3>
				
				<div class="postagem-lateral">
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
					<a href="">Leia mais</a>
				</div>

				<div class="postagem-lateral" style="border-bottom: none;">
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
					<a href="">Leia mais</a>
				</div>

			</div>

			<div class="conteudo-lateral">
				<h3>Categorias</h3>
				
				<a href="">Jogos</a><br>
				<a href="">Celulares</a><br>
				<a href="">Informática</a><br>
				<a href="">Eletrônicos</a><br>
				<a href="">Jogos</a><br>

			</div>


		</div>

		<div id="rodape">
			Todos os direitos reservados
		</div>

	</div>

</body>
</html>